"""Add status to Score model

Revision ID: bfe6335c7048
Revises: 074fb27494fd
Create Date: 2025-04-02 00:32:02.136360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe6335c7048'
down_revision = '074fb27494fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjust for SQLite ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='PENDING'))
        batch_op.alter_column('overall_score',
                   existing_type=sa.FLOAT(),
                   nullable=True)
        batch_op.create_index(batch_op.f('ix_scores_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjust for SQLite ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_status'))
        batch_op.alter_column('overall_score',
                   existing_type=sa.FLOAT(),
                   nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ### 